### ISSUE TITLE
Align1D Problem

### ISSUE THREAD

**Issue by yxy32** [xlliu7/E2E-TAD#3]
Thanks for your nice work. I am trying to try my dataset using your code and  encountered a problem said cannot import name 'Align1D' from partially initialized module 'models.ops.roi_align'. I guess it may be a g-tad problem so I tried to install it. However, when I install g-tad, pycharm shows ' \\visual studio\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120'. Could you help me?

**Comment by yxy32** [comment]
I missed the step of Compiling CUDA extensions. Currently the issue has been fixed.

**Comment by zjutangk** [comment]
> I missed the step of Compiling CUDA extensions. Currently the issue has been fixed.

How you solve it? I have the same problem.
