### ISSUE TITLE
_pickle.UnpicklingError: could not find MARK

### ISSUE THREAD

**Issue by Hank5120** [xlliu7/E2E-TAD#4]
Hi @xlliu7 ,
Thank  you so much for your wonderful work.
I have a problem when I use following method to test Pre-trained Models,

python main.py --cfg configs/thumos14_e2e_slowfast_tadtr.yml --eval --resume scripts/test_reference_models_e2e.sh

And I got this error, I don't know why.

magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

**Comment by Hank5120** [comment]
![Screenshot from 2022-12-08 12-55-14](https://user-images.githubusercontent.com/116187090/206360111-d119af66-f176-4d3a-9059-2ef44c8c804b.png)

**Comment by xlliu7** [comment]
Hi, your command is incorrect. Your command will use "scripts/test_reference_models_e2e.sh" as the weight file, which is apparently invalid. Try `bash scripts/test_reference_models_e2e.sh thumos14` instead.
